1:
	gcc `pkg-config --cflags gtk+-2.0` -o gtk_1 gtk_1.c `pkg-config --libs gtk+-2.0`
	./gtk_1

2:
	gcc `pkg-config --cflags gtk+-2.0` -o gtk_2 gtk_2.c `pkg-config --libs gtk+-2.0`
	./gtk_2

4:
	gcc `pkg-config --cflags gtk+-3.0` -o gtk_4 gtk_4.c `pkg-config --libs gtk+-3.0`
	./gtk_4
